You are a health care team member working in a small clinic that manages a significant number of patients with chronic conditions, such as diabetes and hypertension. The clinic administrator has come to your team with an alarming issue. A significant number of patients are noncompliant in their medication schedules. Noncompliance can lead to worsening conditions, increased hospital visits, and overall poorer patient outcomes. To help manage this, your administrator wants to develop a simple Python-based system to track and remind patients about their medication schedules.

The purpose of this assignment is to develop a simple Python-based system that tracks medication schedules and provides reminders to patients.

Using Python script, perform the following tasks for seven patients with at least three medications:

- Store patient information (name, age, condition, medication list) in compliance with HIPAA regulations.
- Track medication schedules (name of medication, dosage, frequency, and time of day).
- Create a function that checks the current time against the medication schedule.
- Send reminders (simulated by print statements) to the patient when it is time to take their medication.
- Use loops to simulate time passing and trigger reminders.
- Generate reports on missed medications to help the care team follow up with patients.
- Track missed reminders and generate a report that lists all missed doses.

In [92]:
#Store patient information (name, age, condition, medication list) in compliance with HIPAA regulations.

import pandas as pd

df = pd.read_csv('hipaa_compliant_patient_data.csv')
df

  Patient ID  Age     Condition                              Medication List
0     PT-001   58      Diabetes          Metformin, Lisinopril, Atorvastatin
1     PT-002   67  Hypertension  Amlodipine, Hydrochlorothiazide, Lisinopril
2     PT-003   72      Diabetes               Glipizide, Metformin, Losartan
3     PT-004   60  Hypertension          Amlodipine, Lisinopril, Simvastatin
4     PT-005   65      Diabetes               Insulin, Metformin, Lisinopril
5     PT-006   70  Hypertension    Atenolol, Hydrochlorothiazide, Lisinopril
6     PT-007   66      Diabetes             Insulin, Metformin, Atorvastatin

In [93]:
#Track medication schedules (name of medication, dosage, frequency, and time of day).

df2 = pd.read_csv('medication_schedule.csv')
df2

   Patient ID   Name of Medication    Dosage  Frequency (per day) Time of Day
0      PT-001            Metformin     500mg                    2       08:00
1      PT-001            Metformin     500mg                    2       20:00
2      PT-001           Lisinopril      10mg                    1       09:00
3      PT-001         Atorvastatin      20mg                    1       21:00
4      PT-002           Amlodipine       5mg                    1       07:00
5      PT-002  Hydrochlorothiazide      25mg                    1       08:00
6      PT-002           Lisinopril      10mg                    1       20:00
7      PT-003            Glipizide       5mg                    1       08:30
8      PT-003            Metformin     500mg                    2       08:00
9      PT-003            Metformin     500mg                    2       20:00
10     PT-003             Losartan      50mg                    1       21:00
11     PT-004           Amlodipine       5mg                    1       07:30
12     PT-004           Lisinopril      10mg                    1       08:30
13     PT-004          Simvastatin      20mg                    1       20:30
14     PT-005              Insulin  10 units                    3       07:00
15     PT-005              Insulin  10 units                    3       12:00
16     PT-005              Insulin  10 units                    3       18:00
17     PT-005            Metformin     500mg                    2       08:00
18     PT-005            Metformin     500mg                    2       20:00
19     PT-005           Lisinopril      10mg                    1       21:00
20     PT-006             Atenolol      50mg                    1       09:00
21     PT-006  Hydrochlorothiazide      25mg                    1       08:00
22     PT-006           Lisinopril      10mg                    1       20:00
23     PT-007              Insulin  15 units                    3       06:00
24     PT-007              Insulin  15 units                    3       12:00
25     PT-007              Insulin  15 units                    3       18:00
26     PT-007            Metformin     500mg                    2       07:00
27     PT-007            Metformin     500mg                    2       19:00
28     PT-007         Atorvastatin      20mg                    1       20:00

In [94]:
#Create a function that checks the current time against the medication schedule.

def check_medication_schedule(current_time, medication_schedule):
    reminders = []
    for index, row in medication_schedule.iterrows():
        if row['Time of Day'] == current_time:
            reminders.append(
                f"Patient {row['Patient ID']}: Time to take {row['Name of Medication']} at {row['Time of Day']} with dosage {row['Dosage']}."
            )
    return reminders

In [95]:
#Send Reminders (simulated by print statements) to the patient when it is time to take their medication.
def send_reminders(reminders):
    for reminder in reminders:
        print(reminder)

In [96]:
# Use loops to simulate time passing and trigger reminders.
import time
from datetime import datetime

# Get current system time in HH:MM format
system_time = datetime.now().strftime("%H:%M")
print(f"Current System Time: {system_time}")

unique_times = sorted(df2['Time of Day'].unique())

# Create checked_times: all times up to and including the current system time
checked_times = [t for t in unique_times if t <= system_time]

print(f"Checked Times (up to system time): {checked_times}")

# Simulate time passing and trigger reminders for each checked time
for current_time in checked_times:
    print(f"\n--- Current Time: {current_time} ---")
    reminders = check_medication_schedule(current_time, df2)
    send_reminders(reminders)
    time.sleep(1)  # Simulate time passing 

# Generate reports on missed medications (not yet reminded)
missed_medications = df2[~df2['Time of Day'].isin(checked_times)]
missed_report = missed_medications[['Patient ID', 'Name of Medication', 'Dosage', 'Time of Day']]
print("\nMissed Medications Report:")
print(missed_report)

#Track missed reminders and generate a report that lists all missed doses.
missed_report.to_csv('missed_reminders_report.csv', index=False)
print("Missed reminders report saved to 'missed_reminders_report.csv'.")

Current System Time: 13:38
Checked Times (up to system time): ['06:00', '07:00', '07:30', '08:00', '08:30', '09:00', '12:00']

--- Current Time: 06:00 ---
Patient PT-007: Time to take Insulin at 06:00 with dosage 15 units.

--- Current Time: 07:00 ---
Patient PT-002: Time to take Amlodipine at 07:00 with dosage 5mg.
Patient PT-005: Time to take Insulin at 07:00 with dosage 10 units.
Patient PT-007: Time to take Metformin at 07:00 with dosage 500mg.

--- Current Time: 07:30 ---
Patient PT-004: Time to take Amlodipine at 07:30 with dosage 5mg.

--- Current Time: 08:00 ---
Patient PT-001: Time to take Metformin at 08:00 with dosage 500mg.
Patient PT-002: Time to take Hydrochlorothiazide at 08:00 with dosage 25mg.
Patient PT-003: Time to take Metformin at 08:00 with dosage 500mg.
Patient PT-005: Time to take Metformin at 08:00 with dosage 500mg.
Patient PT-006: Time to take Hydrochlorothiazide at 08:00 with dosage 25mg.

--- Current Time: 08:30 ---
Patient PT-003: Time to take Glipizide at 08:30 with dosage 5mg.
Patient PT-004: Time to take Lisinopril at 08:30 with dosage 10mg.

--- Current Time: 09:00 ---
Patient PT-001: Time to take Lisinopril at 09:00 with dosage 10mg.
Patient PT-006: Time to take Atenolol at 09:00 with dosage 50mg.

--- Current Time: 12:00 ---
Patient PT-005: Time to take Insulin at 12:00 with dosage 10 units.
Patient PT-007: Time to take Insulin at 12:00 with dosage 15 units.

Missed Medications Report:
   Patient ID Name of Medication    Dosage Time of Day
1      PT-001          Metformin     500mg       20:00
3      PT-001       Atorvastatin      20mg       21:00
6      PT-002         Lisinopril      10mg       20:00
9      PT-003          Metformin     500mg       20:00
10     PT-003           Losartan      50mg       21:00
13     PT-004        Simvastatin      20mg       20:30
16     PT-005            Insulin  10 units       18:00
18     PT-005          Metformin     500mg       20:00
19     PT-005         Lisinopril      10mg       21:00
22     PT-006         Lisinopril      10mg       20:00
25     PT-007            Insulin  15 units       18:00
27     PT-007          Metformin     500mg       19:00
28     PT-007       Atorvastatin      20mg       20:00
Missed reminders report saved to 'missed_reminders_report.csv'.

Develop a 5-7-slide PowerPoint that describes the patient medication tracking system, including a recommendation on whether to implement it. Include an additional slide at the beginning for the title and an additional slide for references at the end. Create speaker notes of 100-250 words for each slide.

Be sure to embed the following information into your presentation:

- A data table containing each patient's name, age, condition, and medication list.
- A medication schedule for each patient that includes the name of medication, dosage, frequency, and time of day.
- A table of missed medications to help the care team follow up with patients.
- A table of all missed doses.
- Screenshots of the code used to generate the data table.